# Number of layer
nb_layer: 2

# Number of input neurones
nb_input: 720

# Number of hidden neurones
nb_hidden: 100

# Number of output neurones
nb_output: 10

# Activation function
activation: "sigmoid"

# Filter used on the data
filter: static

